### ISSUE TITLE
java.lang.IndexOutOfBoundsException: setSpan (17 ... 22) ends beyond length 18

### ISSUE THREAD

**Issue by cylonu87** [PrivacyApps/html-textview#133]
Hi,

I have a crash when I try to render this HTML:
`<table><tr><td><center>test</center></td></tr></table>`

```
java.lang.IndexOutOfBoundsException: setSpan (17 ... 22) ends beyond length 18
	at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1265)
	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:684)
	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:677)
	at org.sufficientlysecure.htmltextview.HtmlTagHandler.end(HtmlTagHandler.java:333)
	at org.sufficientlysecure.htmltextview.HtmlTagHandler.handleTag(HtmlTagHandler.java:242)
	at android.text.HtmlToSpannedConverter.handleEndTag(Html.java:908)
	at android.text.HtmlToSpannedConverter.endElement(Html.java:1225)
	at org.ccil.cowan.tagsoup.Parser.pop(Parser.java:737)
	at org.ccil.cowan.tagsoup.Parser.etag_basic(Parser.java:707)
	at org.ccil.cowan.tagsoup.Parser.etag(Parser.java:645)
	at org.ccil.cowan.tagsoup.HTMLScanner.scan(HTMLScanner.java:552)
	at org.ccil.cowan.tagsoup.Parser.parse(Parser.java:450)
	at android.text.HtmlToSpannedConverter.convert(Html.java:758)
	at android.text.Html.fromHtml(Html.java:245)
	at android.text.Html.fromHtml(Html.java:219)
	at org.sufficientlysecure.htmltextview.HtmlTextView.setHtml(HtmlTextView.java:98)
```

I did some tests and it crashes because of the `<center>` inside the `<td>`. If I replace `<center>` by `<strong>`, `<i>`, ... it doesn't crash. If the `<center>` is outside the table, it doesn't crash.

**Comment by dschuermann** [comment]
Don't put center in the table ;)
This library is highly constrained to work with only simple HTML
